// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	/**  Return all registered workspaces. */
	workspaceList: () => typedError<WorkspaceInfo[], AppError>(__TAURI_INVOKE("workspace_list")),
	/**  Return the currently active workspace. */
	workspaceGetActive: () => typedError<WorkspaceInfo, AppError>(__TAURI_INVOKE("workspace_get_active")),
	/**  Create a new workspace and switch to it. */
	workspaceCreate: (name: string, copySettings: boolean | null) => typedError<WorkspaceInfo, AppError>(__TAURI_INVOKE("workspace_create", { name, copySettings })),
	/**  Register a backend (cloud) workspace in the local registry. */
	workspaceRegisterCloud: (id: string, name: string, orgId: string | null, ownerId: string | null, workspaceType: string | null, createdAt: string | null) => typedError<WorkspaceInfo, AppError>(__TAURI_INVOKE("workspace_register_cloud", { id, name, orgId, ownerId, workspaceType, createdAt })),
	/**  Switch the active workspace. The frontend must reload stores after this. */
	workspaceSwitch: (id: string) => typedError<null, AppError>(__TAURI_INVOKE("workspace_switch", { id })),
	/**  Rename a workspace. */
	workspaceRename: (id: string, name: string) => typedError<null, AppError>(__TAURI_INVOKE("workspace_rename", { id, name })),
	/**
	 *  Delete a workspace. Cannot delete the currently active workspace.
	 *  The workspace directory and all its data are removed.
	 */
	workspaceDelete: (id: string) => typedError<null, AppError>(__TAURI_INVOKE("workspace_delete", { id })),
};

/* Types */
export type AppError = ({ Io: string }) & { Crypto?: never; Other?: never; Serialization?: never } | ({ Crypto: string }) & { Io?: never; Other?: never; Serialization?: never } | ({ Serialization: string }) & { Crypto?: never; Io?: never; Other?: never } | "WrongPassword" | "EncryptionLocked" | ({ Other: string }) & { Crypto?: never; Io?: never; Serialization?: never };

export type WorkspaceInfo = {
	id: string,
	name: string,
	createdAt: string,
	workspaceType: string,
	orgId: string | null,
	ownerId: string | null,
	cloudSync: boolean,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

