// AUTO-GENERATED by gen-specta. Do not edit manually.
// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	appInfo: () => typedError<AppInfo, AppError>(__TAURI_INVOKE("app_info")),
	appDirectory: () => typedError<string, AppError>(__TAURI_INVOKE("app_directory")),
	migrationStatus: () => typedError<LegacyMigrationStatus, AppError>(__TAURI_INVOKE("migration_status")),
	migrationRun: () => typedError<LegacyMigrationResult, AppError>(__TAURI_INVOKE("migration_run")),
	migrationProbePath: (path: string) => typedError<LegacyMigrationStatus, AppError>(__TAURI_INVOKE("migration_probe_path", { path })),
	migrationRunWithPath: (path: string) => typedError<LegacyMigrationResult, AppError>(__TAURI_INVOKE("migration_run_with_path", { path })),
	migrationReadLegacyData: (dir: string) => typedError<string | null, AppError>(__TAURI_INVOKE("migration_read_legacy_data", { dir })),
	migrationWriteLegacyData: (dir: string, content: string) => typedError<null, AppError>(__TAURI_INVOKE("migration_write_legacy_data", { dir, content })),
	showNotification: (title: string, body: string) => typedError<null, AppError>(__TAURI_INVOKE("show_notification", { title, body })),
	setSpellcheck: (enabled: boolean) => typedError<null, AppError>(__TAURI_INVOKE("set_spellcheck", { enabled })),
	setZoom: (level: number | null) => typedError<null, AppError>(__TAURI_INVOKE("set_zoom", { level })),
	getZoom: () => typedError<number | null, AppError>(__TAURI_INVOKE("get_zoom")),
	setReducedMotion: (enabled: boolean) => typedError<null, AppError>(__TAURI_INVOKE("set_reduced_motion", { enabled })),
	getReducedMotion: () => typedError<boolean, AppError>(__TAURI_INVOKE("get_reduced_motion")),
	setHighContrast: (enabled: boolean) => typedError<null, AppError>(__TAURI_INVOKE("set_high_contrast", { enabled })),
	getHighContrast: () => typedError<boolean, AppError>(__TAURI_INVOKE("get_high_contrast")),
	changeMenuVisibility: (visible: boolean) => typedError<null, AppError>(__TAURI_INVOKE("change_menu_visibility", { visible })),
	appReady: () => typedError<null, AppError>(__TAURI_INVOKE("app_ready")),
	helperRelaunch: () => typedError<null, AppError>(__TAURI_INVOKE("helper_relaunch")),
	helperGetPath: (name: string) => typedError<string, AppError>(__TAURI_INVOKE("helper_get_path", { name })),
	helperIsDarkTheme: () => typedError<boolean, AppError>(__TAURI_INVOKE("helper_is_dark_theme")),
	showEditContextMenu: (x: number | null, y: number | null) => typedError<null, AppError>(__TAURI_INVOKE("show_edit_context_menu", { x, y })),
	/**
	 *  Export a full-state backup folder (clean DB copies + global assets):
	 *  `<dir>/data.db`, `<dir>/settings.db`, `<dir>/assets/`
	 */
	backupExport: (dir: string) => typedError<null, AppError>(__TAURI_INVOKE("backup_export", { dir })),
	/**
	 *  Import a backup folder from `backup_export`: replaces every row of both
	 *  live DBs and swaps the assets directory. Caller must relaunch afterwards so
	 *  cached state rehydrates.
	 */
	backupImport: (dir: string) => typedError<null, AppError>(__TAURI_INVOKE("backup_import", { dir })),
	openFileExternal: (src: string) => typedError<string, AppError>(__TAURI_INVOKE("open_file_external", { src })),
	fsCopy: (path: string, dest: string) => typedError<null, AppError>(__TAURI_INVOKE("fs_copy", { path, dest })),
	fsOutputJson: (path: string, data: RawJson) => typedError<null, AppError>(__TAURI_INVOKE("fs_output_json", { path, data })),
	fsReadJson: (path: string) => typedError<RawJson, AppError>(__TAURI_INVOKE("fs_read_json", { path })),
	fsEnsureDir: (path: string) => typedError<null, AppError>(__TAURI_INVOKE("fs_ensure_dir", { path })),
	fsPathExists: (path: string) => typedError<boolean, AppError>(__TAURI_INVOKE("fs_path_exists", { path })),
	fsRemove: (path: string) => typedError<null, AppError>(__TAURI_INVOKE("fs_remove", { path })),
	fsWriteFile: (path: string, data: string, mode: number | null) => typedError<null, AppError>(__TAURI_INVOKE("fs_write_file", { path, data, mode })),
	fsMkdir: (path: string, mode: number | null) => typedError<null, AppError>(__TAURI_INVOKE("fs_mkdir", { path, mode })),
	fsReadFile: (path: string) => typedError<string, AppError>(__TAURI_INVOKE("fs_read_file", { path })),
	fsReadFileBinary: (path: string) => typedError<string, AppError>(__TAURI_INVOKE("fs_read_file_binary", { path })),
	fsReaddir: (path: string) => typedError<string[], AppError>(__TAURI_INVOKE("fs_readdir", { path })),
	fsStat: (path: string) => typedError<FileStat, AppError>(__TAURI_INVOKE("fs_stat", { path })),
	/**
	 *  System icon for a file, as base64 PNG. Cached by extension; the frontend
	 *  falls back to a generic icon when this errors (mobile, missing file).
	 */
	fsFileIcon: (path: string, size: number | null) => typedError<string, AppError>(__TAURI_INVOKE("fs_file_icon", { path, size })),
	fsUnlink: (path: string) => typedError<null, AppError>(__TAURI_INVOKE("fs_unlink", { path })),
	fsReadData: (path: string, skipDecryption: boolean | null) => typedError<string, AppError>(__TAURI_INVOKE("fs_read_data", { path, skipDecryption })),
	fsIsFile: (path: string) => typedError<boolean, AppError>(__TAURI_INVOKE("fs_is_file", { path })),
	fsAccess: (path: string) => typedError<boolean, AppError>(__TAURI_INVOKE("fs_access", { path })),
	fsDownloadUrl: (url: string, dest: string) => typedError<number, AppError>(__TAURI_INVOKE("fs_download_url", { url, dest })),
	/**
	 *  Full store as nested JSON, only startup/sync (loads everything). Content not encrypted at KV layer.
	 *  Yjs blobs encrypted in note_content/yjs_snapshots. DB read plus decrypt on blocking thread.
	 */
	storageGetStore: (name: string) => typedError<RawJson, AppError>(__TAURI_INVOKE("storage_get_store", { name })),
	/**  Replace entire store (sync/import). Only changed rows re-encrypted and written, avoids AES-GCM and I/O. Blocking thread. */
	storageReplace: (name: string, data: RawJson) => typedError<null, AppError>(__TAURI_INVOKE("storage_replace", { name, data })),
	/**
	 *  Get one value by dot-separated key: single-row lookup for flat keys, else full-store load (legacy).
	 *  Runs off main thread: collection fallback reads and decrypts entire KV table.
	 */
	storageGet: (name: string, key: string, def: RawJson) => typedError<RawJson, AppError>(__TAURI_INVOKE("storage_get", { name, key, def })),
	/**
	 *  Set one value by dot-separated key: single INSERT OR REPLACE for
	 *  flat-addressable keys, otherwise the load-modify-rewrite path.
	 */
	storageSet: (name: string, key: string, value: RawJson) => typedError<null, AppError>(__TAURI_INVOKE("storage_set", { name, key, value })),
	/**
	 *  Delete one value by dot-separated key: single DELETE for flat-addressable
	 *  keys, otherwise the load-modify-rewrite path.
	 */
	storageDelete: (name: string, key: string) => typedError<null, AppError>(__TAURI_INVOKE("storage_delete", { name, key })),
	/**  Whether a key exists (COUNT for flat-addressable keys, otherwise fallback). */
	storageHas: (name: string, key: string) => typedError<boolean, AppError>(__TAURI_INVOKE("storage_has", { name, key })),
	storageClear: (name: string) => typedError<null, AppError>(__TAURI_INVOKE("storage_clear", { name })),
	/**
	 *  Whole-row-encrypt legacy plaintext `notes.*` / `folders.*` rows.
	 *  Idempotent; call after the app key is loaded.
	 */
	storageReencryptLegacyRows: () => typedError<number, AppError>(__TAURI_INVOKE("storage_reencrypt_legacy_rows")),
	storageRepairSettings: () => typedError<number, AppError>(__TAURI_INVOKE("storage_repair_settings")),
	safeStorageIsAvailable: () => typedError<boolean, AppError>(__TAURI_INVOKE("safe_storage_is_available")),
	safeStorageGetBackendInfo: () => typedError<SafeStorageBackendInfo, AppError>(__TAURI_INVOKE("safe_storage_get_backend_info")),
	safeStorageEncrypt: (plainText: string) => typedError<string, AppError>(__TAURI_INVOKE("safe_storage_encrypt", { plainText })),
	safeStorageDecrypt: (encryptedBase64: string) => typedError<string, AppError>(__TAURI_INVOKE("safe_storage_decrypt", { encryptedBase64 })),
	safeStorageStoreBlob: (key: string, blob: string) => typedError<null, AppError>(__TAURI_INVOKE("safe_storage_store_blob", { key, blob })),
	safeStorageFetchBlob: (key: string) => typedError<string | null, AppError>(__TAURI_INVOKE("safe_storage_fetch_blob", { key })),
	safeStorageClearBlob: (key: string) => typedError<null, AppError>(__TAURI_INVOKE("safe_storage_clear_blob", { key })),
	safeStorageSetDevicePassword: (password: string) => typedError<null, AppError>(__TAURI_INVOKE("safe_storage_set_device_password", { password })),
	assetCryptoSetPassphrase: (passphrase: string) => typedError<null, AppError>(__TAURI_INVOKE("asset_crypto_set_passphrase", { passphrase })),
	assetCryptoClearPassphrase: () => typedError<null, AppError>(__TAURI_INVOKE("asset_crypto_clear_passphrase")),
	assetCryptoMigrateDir: () => typedError<AssetMigrationResult, AppError>(__TAURI_INVOKE("asset_crypto_migrate_dir")),
	encryptionGetState: () => typedError<EncryptionStateResult, AppError>(__TAURI_INVOKE("encryption_get_state")),
	encryptionSubmitPassword: (password: string, createIfMissing: boolean | null) => typedError<EncryptionSubmitResult, AppError>(__TAURI_INVOKE("encryption_submit_password", { password, createIfMissing })),
	encryptionEnable: (password: string) => typedError<null, AppError>(__TAURI_INVOKE("encryption_enable", { password })),
	encryptionUnlock: (password: string) => typedError<null, AppError>(__TAURI_INVOKE("encryption_unlock", { password })),
	encryptionLock: () => typedError<null, AppError>(__TAURI_INVOKE("encryption_lock")),
	encryptionEncryptNotePayload: (plainBytes: number[]) => typedError<RawJson, AppError>(__TAURI_INVOKE("encryption_encrypt_note_payload", { plainBytes })),
	encryptionDecryptNotePayload: (payload: RawJson) => typedError<number[] | null, AppError>(__TAURI_INVOKE("encryption_decrypt_note_payload", { payload })),
	/**
	 *  Encrypt sync payload (commit/snapshot/genesis) with items key (XChaCha20-Poly1305). AAD binds identity, blocks swapping.
	 *  Update is base64 raw bytes, never JSON number arrays. Meta inside envelope.
	 */
	syncEncryptPayload: (meta: string, data: string, aad: string) => typedError<string, AppError>(__TAURI_INVOKE("sync_encrypt_payload", { meta, data, aad })),
	/**
	 *  Decrypt sync payload: DECRYPT_FAILED on auth failure (wrong passphrase, tampered AAD), KEY_LOCKED if absent.
	 *  Update returns base64 raw bytes; v4 JSON number arrays decoded for compat.
	 */
	syncDecryptPayload: (enc: string, aad: string) => typedError<SyncDecryptedPayload, AppError>(__TAURI_INVOKE("sync_decrypt_payload", { enc, aad })),
	/**
	 *  Batch-encrypt sync payloads in parallel. All items must succeed; any
	 *  failure errors the whole batch.
	 */
	syncEncryptBatch: (metas: string[], dataB64s: string[], aads: string[]) => typedError<string[], AppError>(__TAURI_INVOKE("sync_encrypt_batch", { metas, dataB64s, aads })),
	/**
	 *  Batch-decrypt sync payloads in parallel; each envelope is independent and
	 *  failed items yield `None` instead of aborting the batch.
	 */
	syncDecryptBatch: (envelopes: string[], aads: string[]) => typedError<(SyncDecryptedPayload | null)[], AppError>(__TAURI_INVOKE("sync_decrypt_batch", { envelopes, aads })),
	syncKeyReady: () => __TAURI_INVOKE<boolean>("sync_key_ready"),
	/**
	 *  Keep the local manifest and shared `keyParams.json` consistent so every
	 *  device derives the same items key. `passphrase` adopts a remote items key on
	 *  a joining device; it is never written out.
	 */
	encryptionReconcileKeyParams: (passphrase: string | null) => typedError<null, AppError>(__TAURI_INVOKE("encryption_reconcile_key_params", { passphrase })),
	/**
	 *  Join vault by adopting shared key params. Works with inactive session (fresh device).
	 *  Wrong passphrase returns WrongPassword, touches no vault state.
	 */
	encryptionAdoptKeyParams: (passphrase: string, keyParams: string | null) => typedError<EncryptionSubmitResult, AppError>(__TAURI_INVOKE("encryption_adopt_key_params", { passphrase, keyParams })),
	/**
	 *  True when the configured sync source holds key params differing from the
	 *  local manifest (or no local manifest exists).
	 */
	encryptionHasRemoteKeyParams: () => typedError<boolean, AppError>(__TAURI_INVOKE("encryption_has_remote_key_params")),
	passwdHash: (password: string) => typedError<string, AppError>(__TAURI_INVOKE("passwd_hash", { password })),
	passwdCompare: (password: string, hash: string) => typedError<boolean, AppError>(__TAURI_INVOKE("passwd_compare", { password, hash })),
	passwdRecordFailure: () => typedError<FailureResult, AppError>(__TAURI_INVOKE("passwd_record_failure")),
	passwdResetFailures: () => typedError<null, AppError>(__TAURI_INVOKE("passwd_reset_failures")),
	encryptionDecryptAssetStream: (path: string) => typedError<string, AppError>(__TAURI_INVOKE("encryption_decrypt_asset_stream", { path })),
	encryptionEncryptAssetStream: (path: string) => typedError<null, AppError>(__TAURI_INVOKE("encryption_encrypt_asset_stream", { path })),
	encryptionCacheDecryptedNote: (noteId: string, content: number[]) => typedError<null, AppError>(__TAURI_INVOKE("encryption_cache_decrypted_note", { noteId, content })),
	encryptionGetCachedDecryptedNote: (noteId: string) => __TAURI_INVOKE<number[] | null>("encryption_get_cached_decrypted_note", { noteId }),
	encryptionClearDecryptedCaches: () => typedError<null, AppError>(__TAURI_INVOKE("encryption_clear_decrypted_caches")),
	decryptLegacyCryptojsNote: (ciphertextB64: string, password: string) => typedError<string, AppError>(__TAURI_INVOKE("decrypt_legacy_cryptojs_note", { ciphertextB64, password })),
	deriveArgon2Key: (passphrase: string, salt: string | null) => typedError<string, AppError>(__TAURI_INVOKE("derive_argon2_key", { passphrase, salt })),
	vaultDeriveProof: (passphrase: string, workspaceId: string, keyParamsBlob: string) => typedError<string, AppError>(__TAURI_INVOKE("vault_derive_proof", { passphrase, workspaceId, keyParamsBlob })),
	dialogOpen: (props: OpenDialogOptions) => typedError<DialogResult, AppError>(__TAURI_INVOKE("dialog_open", { props })),
	dialogMessage: (props: MessageDialogOptions) => typedError<null, AppError>(__TAURI_INVOKE("dialog_message", { props })),
	dialogSave: (props: SaveDialogOptions) => typedError<SaveDialogResult, AppError>(__TAURI_INVOKE("dialog_save", { props })),
	getSystemFonts: () => typedError<string[], AppError>(__TAURI_INVOKE("get_system_fonts")),
	getInstallationSource: () => __TAURI_INVOKE<InstallationSource>("get_installation_source"),
	checkForUpdates: () => typedError<CheckResult, AppError>(__TAURI_INVOKE("check_for_updates")),
	downloadUpdate: () => typedError<null, AppError>(__TAURI_INVOKE("download_update")),
	installUpdate: () => typedError<null, AppError>(__TAURI_INVOKE("install_update")),
	toggleAutoUpdate: (enabled: boolean) => typedError<null, AppError>(__TAURI_INVOKE("toggle_auto_update", { enabled })),
	getAutoUpdateStatus: () => typedError<boolean, AppError>(__TAURI_INVOKE("get_auto_update_status")),
	isUpdateDownloading: () => typedError<boolean, AppError>(__TAURI_INVOKE("is_update_downloading")),
	getUpdateInfo: () => typedError<UpdateInfo, AppError>(__TAURI_INVOKE("get_update_info")),
	importEvernote: (enexPath: string, notebookName: string | null) => typedError<null, AppError>(__TAURI_INVOKE("import_evernote", { enexPath, notebookName })),
	importAppleNotes: () => typedError<null, AppError>(__TAURI_INVOKE("import_apple_notes")),
	renderPdf: (html: string, outputPath: string) => typedError<null, AppError>(__TAURI_INVOKE("render_pdf", { html, outputPath })),
	/**
	 *  Append one Yjs update as append-only BLOB row (preserves peer versions), encrypted when active.
	 *  Blocking thread; base64 over IPC (~3x smaller than JSON number array).
	 */
	yjsAppend: (noteId: string, update: string, device: string) => typedError<null, AppError>(__TAURI_INVOKE("yjs_append", { noteId, update, device })),
	/**  Append multiple Yjs updates in one IPC call, inside a single SQLite transaction. */
	yjsAppendBatch: (noteIds: string[], updates: string[], devices: string[]) => typedError<number, AppError>(__TAURI_INVOKE("yjs_append_batch", { noteIds, updates, devices })),
	/**  Every stored update for a note, oldest first, for replaying into a Y.Doc. */
	yjsGetUpdates: (noteId: string) => typedError<string[], AppError>(__TAURI_INVOKE("yjs_get_updates", { noteId })),
	/**
	 *  Cached merged snapshot when fresh. Empty means replay history and re-cache via `yjs_save_snapshot`.
	 *  Stale path replays whole history on blocking thread.
	 */
	yjsGetSnapshot: (noteId: string) => typedError<string, AppError>(__TAURI_INVOKE("yjs_get_snapshot", { noteId })),
	/**
	 *  Fresh merged snapshots for many notes in one round-trip (batched SQL, no N+1 IPC).
	 *  Only notes with data included; rayon parallel decrypt on blocking thread.
	 */
	yjsGetSnapshots: (noteIds: string[]) => typedError<{ [key in string]: string }, AppError>(__TAURI_INVOKE("yjs_get_snapshots", { noteIds })),
	/**
	 *  Replace all updates with one compressed snapshot to bound row count.
	 *  Blocking thread: rewrites rows, encrypts multi-MB blob on note switch.
	 */
	yjsCompact: (noteId: string, snapshot: string) => typedError<null, AppError>(__TAURI_INVOKE("yjs_compact", { noteId, snapshot })),
	/**  Merge updates into one snapshot (y-octo), replace rows and sync cache in one SQLite transaction. */
	yjsCompactBatch: (noteId: string) => typedError<null, AppError>(__TAURI_INVOKE("yjs_compact_batch", { noteId })),
	/**  Delete all Yjs updates for a note on note delete. */
	yjsDelete: (noteId: string) => typedError<null, AppError>(__TAURI_INVOKE("yjs_delete", { noteId })),
	indexSave: (searchJson: string, linksJson: string, signaturesJson: string) => typedError<null, AppError>(__TAURI_INVOKE("index_save", { searchJson, linksJson, signaturesJson })),
	indexLoad: () => typedError<{
	searchJson: string,
	linksJson: string,
	signaturesJson: string,
} | null, AppError>(__TAURI_INVOKE("index_load")),
	/**
	 *  Extract search-index data from all notes in the data store, off-main-thread
	 *  via `spawn_blocking`; entries are MiniSearch-ready on the JS side.
	 */
	searchExtractIndexData: () => typedError<SearchEntry[], AppError>(__TAURI_INVOKE("search_extract_index_data")),
	workspaceList: () => typedError<WorkspaceInfo[], AppError>(__TAURI_INVOKE("workspace_list")),
	workspaceGetActive: () => typedError<WorkspaceInfo, AppError>(__TAURI_INVOKE("workspace_get_active")),
	/**  Create a new workspace and switch to it. */
	workspaceCreate: (name: string, copySettings: boolean | null) => typedError<WorkspaceInfo, AppError>(__TAURI_INVOKE("workspace_create", { name, copySettings })),
	/**
	 *  Register a backend (cloud) workspace in the local registry so local mirrors
	 *  of shared workspaces participate in removal reconciliation. Creates the
	 *  directory + DBs on first registration; never changes the active workspace.
	 */
	workspaceRegisterCloud: (id: string, name: string, orgId: string | null, ownerId: string | null, workspaceType: string | null, createdAt: string | null) => typedError<WorkspaceInfo, AppError>(__TAURI_INVOKE("workspace_register_cloud", { id, name, orgId, ownerId, workspaceType, createdAt })),
	/**  Switch the active workspace. The frontend must reload stores after this. */
	workspaceSwitch: (id: string) => typedError<null, AppError>(__TAURI_INVOKE("workspace_switch", { id })),
	workspaceRename: (id: string, name: string) => typedError<null, AppError>(__TAURI_INVOKE("workspace_rename", { id, name })),
	/**  Delete a workspace (never the active or default one); removes its directory. */
	workspaceDelete: (id: string) => typedError<null, AppError>(__TAURI_INVOKE("workspace_delete", { id })),
};

/* Types */
export type AppError = ({ Io: string }) & { Crypto?: never; Other?: never; Serialization?: never } | ({ Crypto: string }) & { Io?: never; Other?: never; Serialization?: never } | ({ Serialization: string }) & { Crypto?: never; Io?: never; Other?: never } | "WrongPassword" | "EncryptionLocked" | "DevicePasswordRequired" | "WrongDevicePassword" | "SecureStorageUnavailable" | ({ Other: string }) & { Crypto?: never; Io?: never; Serialization?: never };

export type AppInfo = {
	name: string,
	version: string,
};

export type AssetMigrationResult = {
	total: number,
	processed: number,
	failedPaths: string[],
};

export type CheckResult = {
	success: boolean,
	available: boolean,
	version: string | null,
	error: string | null,
};

export type DialogFilter = {
	name: string,
	extensions: string[],
};

export type DialogResult = {
	canceled: boolean,
	filePaths: string[],
};

export type EncryptionStateResult = {
	enabled: boolean,
	unlocked: boolean,
	appEnabled: boolean,
	appUnlocked: boolean,
};

export type EncryptionSubmitResult = {
	ok: boolean,
	error: string | null,
	state: EncryptionStateResult,
};

export type FailureResult = {
	failCount: number,
	warn: boolean,
	/**  True when the unlock is currently rate-limited (lockout active). */
	locked: boolean,
	/**  Seconds remaining in the current lockout (0 when not locked). */
	lockoutSeconds: number | null,
};

export type FileStat = {
	isFile: boolean,
	isDirectory: boolean,
	size: number | null,
	mtimeMs: number | null,
	ctimeMs: number | null,
};

export type IndexSnapshot = {
	searchJson: string,
	linksJson: string,
	signaturesJson: string,
};

export type InstallationSource = "standalone" | "scoop" | "brew" | "linux" | "appStore";

export type LegacyMigrationResult = {
	legacyDir: string | null,
	appDir: string | null,
	mergedStoreFiles: string[],
	copiedAssetDirs: string[],
	markerWritten: boolean,
};

export type LegacyMigrationStatus = {
	legacyDir: string | null,
	appDir: string | null,
	hasLegacyData: boolean,
	alreadyMigrated: boolean,
	targetHasData: boolean,
};

/**
 *  Which secure backend currently protects the master key: OS keychain on
 *  macOS/Windows/iOS, Secret Service / kernel keyring on Linux, Android
 *  Keystore on Android. `EncryptedFile` is the Linux device-password fallback.
 */
export type MasterKeyBackendKind = "keychain" | "secretService" | "kernelKeyring" | "encryptedFile" | "androidKeystore" | "none";

export type MessageDialogOptions = {
	title: string | null,
	message: string,
	type: string | null,
	buttons: string[] | null,
};

export type OpenDialogOptions = {
	title: string | null,
	defaultPath: string | null,
	directory: boolean | null,
	multiple: boolean | null,
	properties: string[] | null,
	filters: DialogFilter[] | null,
};

/**
 *  Wrapper around `serde_json::Value` that specta exports as TypeScript `any`.
 *  This avoids the infinite-loop bug in specta-typescript when trying to render
 *  the recursive `serde_json::Value` enum definition.
 */
export type RawJson = any;

export type SafeStorageBackendInfo = {
	available: boolean,
	backend: MasterKeyBackendKind,
	devicePasswordRequired: boolean,
};

export type SaveDialogOptions = {
	title: string | null,
	defaultPath: string | null,
	filters: DialogFilter[] | null,
};

export type SaveDialogResult = {
	canceled: boolean,
	filePath: string | null,
};

export type SearchEntry = {
	id: string,
	title: string,
	searchText: string,
	labelsText: string,
};

export type SyncDecryptedPayload = {
	meta: SyncMeta,
	update: string,
};

export type SyncMeta = {
	device: string,
	ts: number,
	sequence?: number | null,
	noteId: string,
};

export type UpdateInfo = {
	isChecking: boolean,
	isDownloading: boolean,
	currentVersion: string | null,
	availableVersion: string | null,
	autoUpdateEnabled: boolean,
	isBusy: boolean,
};

export type WorkspaceInfo = {
	id: string,
	name: string,
	createdAt: string,
	workspaceType?: string,
	orgId?: string | null,
	ownerId?: string | null,
	cloudSync?: boolean,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

