// AUTO-GENERATED by gen-specta. Do not edit manually.
// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	appInfo: () => typedError<AppInfo, AppError>(__TAURI_INVOKE("app_info")),
	appDirectory: () => typedError<string, AppError>(__TAURI_INVOKE("app_directory")),
	migrationStatus: () => typedError<LegacyMigrationStatus, AppError>(__TAURI_INVOKE("migration_status")),
	migrationRun: () => typedError<LegacyMigrationResult, AppError>(__TAURI_INVOKE("migration_run")),
	migrationProbePath: (path: string) => typedError<LegacyMigrationStatus, AppError>(__TAURI_INVOKE("migration_probe_path", { path })),
	migrationRunWithPath: (path: string) => typedError<LegacyMigrationResult, AppError>(__TAURI_INVOKE("migration_run_with_path", { path })),
	migrationReadLegacyData: (dir: string) => typedError<string | null, AppError>(__TAURI_INVOKE("migration_read_legacy_data", { dir })),
	migrationWriteLegacyData: (dir: string, content: string) => typedError<null, AppError>(__TAURI_INVOKE("migration_write_legacy_data", { dir, content })),
	showNotification: (title: string, body: string) => typedError<null, AppError>(__TAURI_INVOKE("show_notification", { title, body })),
	setSpellcheck: (enabled: boolean) => typedError<null, AppError>(__TAURI_INVOKE("set_spellcheck", { enabled })),
	setZoom: (level: number | null) => typedError<null, AppError>(__TAURI_INVOKE("set_zoom", { level })),
	getZoom: () => typedError<number | null, AppError>(__TAURI_INVOKE("get_zoom")),
	setReducedMotion: (enabled: boolean) => typedError<null, AppError>(__TAURI_INVOKE("set_reduced_motion", { enabled })),
	getReducedMotion: () => typedError<boolean, AppError>(__TAURI_INVOKE("get_reduced_motion")),
	setHighContrast: (enabled: boolean) => typedError<null, AppError>(__TAURI_INVOKE("set_high_contrast", { enabled })),
	getHighContrast: () => typedError<boolean, AppError>(__TAURI_INVOKE("get_high_contrast")),
	changeMenuVisibility: (visible: boolean) => typedError<null, AppError>(__TAURI_INVOKE("change_menu_visibility", { visible })),
	appReady: () => typedError<null, AppError>(__TAURI_INVOKE("app_ready")),
	helperRelaunch: () => typedError<null, AppError>(__TAURI_INVOKE("helper_relaunch")),
	helperGetPath: (name: string) => typedError<string, AppError>(__TAURI_INVOKE("helper_get_path", { name })),
	helperIsDarkTheme: () => typedError<boolean, AppError>(__TAURI_INVOKE("helper_is_dark_theme")),
	showEditContextMenu: (x: number | null, y: number | null) => typedError<null, AppError>(__TAURI_INVOKE("show_edit_context_menu", { x, y })),
	openFileExternal: (src: string) => typedError<string, AppError>(__TAURI_INVOKE("open_file_external", { src })),
	fsCopy: (path: string, dest: string) => typedError<null, AppError>(__TAURI_INVOKE("fs_copy", { path, dest })),
	fsOutputJson: (path: string, data: RawJson) => typedError<null, AppError>(__TAURI_INVOKE("fs_output_json", { path, data })),
	fsReadJson: (path: string) => typedError<RawJson, AppError>(__TAURI_INVOKE("fs_read_json", { path })),
	fsEnsureDir: (path: string) => typedError<null, AppError>(__TAURI_INVOKE("fs_ensure_dir", { path })),
	fsPathExists: (path: string) => typedError<boolean, AppError>(__TAURI_INVOKE("fs_path_exists", { path })),
	fsRemove: (path: string) => typedError<null, AppError>(__TAURI_INVOKE("fs_remove", { path })),
	fsWriteFile: (path: string, data: string, mode: number | null) => typedError<null, AppError>(__TAURI_INVOKE("fs_write_file", { path, data, mode })),
	fsMkdir: (path: string, mode: number | null) => typedError<null, AppError>(__TAURI_INVOKE("fs_mkdir", { path, mode })),
	fsReadFile: (path: string) => typedError<string, AppError>(__TAURI_INVOKE("fs_read_file", { path })),
	fsReadFileBinary: (path: string) => typedError<string, AppError>(__TAURI_INVOKE("fs_read_file_binary", { path })),
	fsReaddir: (path: string) => typedError<string[], AppError>(__TAURI_INVOKE("fs_readdir", { path })),
	fsStat: (path: string) => typedError<FileStat, AppError>(__TAURI_INVOKE("fs_stat", { path })),
	fsUnlink: (path: string) => typedError<null, AppError>(__TAURI_INVOKE("fs_unlink", { path })),
	fsReadData: (path: string, skipDecryption: boolean | null) => typedError<string, AppError>(__TAURI_INVOKE("fs_read_data", { path, skipDecryption })),
	fsIsFile: (path: string) => typedError<boolean, AppError>(__TAURI_INVOKE("fs_is_file", { path })),
	fsAccess: (path: string) => typedError<boolean, AppError>(__TAURI_INVOKE("fs_access", { path })),
	fsDownloadUrl: (url: string, dest: string) => typedError<number, AppError>(__TAURI_INVOKE("fs_download_url", { url, dest })),
	/**
	 *  Returns the full store as a nested JSON object.
	 *  Only used on startup / sync — intentionally loads everything.
	 *  Note content is no longer encrypted at the KV layer; Yjs blobs are
	 *  encrypted at rest in the note_content / yjs_snapshots tables instead.
	 * 
	 *  The heavy lifting (DB read + per-row decryption) is dispatched to a
	 *  blocking thread pool so the Tauri event loop stays responsive.
	 */
	storageGetStore: (name: string) => typedError<RawJson, AppError>(__TAURI_INVOKE("storage_get_store", { name })),
	/**
	 *  Replaces the entire store. Used by sync / import flows.
	 * 
	 *  Optimised path: only rows whose content actually changed are re-encrypted
	 *  and written.  Unchanged rows keep their existing DB envelope, avoiding
	 *  expensive AES-GCM re-encryption and reducing I/O.
	 * 
	 *  Heavy lifting (full-table read + per-row compare/decrypt/encrypt) is
	 *  dispatched to a blocking thread so the Tauri event loop stays responsive.
	 */
	storageReplace: (name: string, data: RawJson) => typedError<null, AppError>(__TAURI_INVOKE("storage_replace", { name, data })),
	/**
	 *  Gets a single value by dot-separated key.
	 *  For flat-addressable keys this is a single-row lookup; otherwise it falls
	 *  back to loading the full store (legacy path, rarely hit).
	 * 
	 *  Runs off the main thread: the collection-namespace fallback ("notes",
	 *  "folders") reads and decrypts the entire KV table, which must not block the
	 *  Tauri event loop.
	 */
	storageGet: (name: string, key: string, def: RawJson) => typedError<RawJson, AppError>(__TAURI_INVOKE("storage_get", { name, key, def })),
	/**
	 *  Sets a single value by dot-separated key.
	 *  For flat-addressable keys this is a single INSERT OR REPLACE; otherwise it
	 *  falls back to the load-modify-rewrite path.
	 */
	storageSet: (name: string, key: string, value: RawJson) => typedError<null, AppError>(__TAURI_INVOKE("storage_set", { name, key, value })),
	/**
	 *  Deletes a single value by dot-separated key.
	 *  For flat-addressable keys this is a single DELETE; otherwise falls back to
	 *  the load-modify-rewrite path.
	 */
	storageDelete: (name: string, key: string) => typedError<null, AppError>(__TAURI_INVOKE("storage_delete", { name, key })),
	/**
	 *  Checks whether a key exists.
	 *  For flat-addressable keys this is a single COUNT query; otherwise falls back.
	 */
	storageHas: (name: string, key: string) => typedError<boolean, AppError>(__TAURI_INVOKE("storage_has", { name, key })),
	storageClear: (name: string) => typedError<null, AppError>(__TAURI_INVOKE("storage_clear", { name })),
	/**
	 *  Whole-row-encrypt legacy `notes.*` / `folders.*` rows left plaintext by the
	 *  migration. Idempotent; call after the app key is loaded.
	 */
	storageReencryptLegacyRows: () => typedError<number, AppError>(__TAURI_INVOKE("storage_reencrypt_legacy_rows")),
	safeStorageIsAvailable: () => typedError<boolean, AppError>(__TAURI_INVOKE("safe_storage_is_available")),
	safeStorageGetBackendInfo: () => typedError<SafeStorageBackendInfo, AppError>(__TAURI_INVOKE("safe_storage_get_backend_info")),
	safeStorageEncrypt: (plainText: string) => typedError<string, AppError>(__TAURI_INVOKE("safe_storage_encrypt", { plainText })),
	safeStorageDecrypt: (encryptedBase64: string) => typedError<string, AppError>(__TAURI_INVOKE("safe_storage_decrypt", { encryptedBase64 })),
	safeStorageStoreBlob: (key: string, blob: string) => typedError<null, AppError>(__TAURI_INVOKE("safe_storage_store_blob", { key, blob })),
	safeStorageFetchBlob: (key: string) => typedError<string | null, AppError>(__TAURI_INVOKE("safe_storage_fetch_blob", { key })),
	safeStorageClearBlob: (key: string) => typedError<null, AppError>(__TAURI_INVOKE("safe_storage_clear_blob", { key })),
	safeStorageSetDevicePassword: (password: string) => typedError<null, AppError>(__TAURI_INVOKE("safe_storage_set_device_password", { password })),
	assetCryptoSetPassphrase: (passphrase: string) => typedError<null, AppError>(__TAURI_INVOKE("asset_crypto_set_passphrase", { passphrase })),
	assetCryptoClearPassphrase: () => typedError<null, AppError>(__TAURI_INVOKE("asset_crypto_clear_passphrase")),
	assetCryptoMigrateDir: () => typedError<AssetMigrationResult, AppError>(__TAURI_INVOKE("asset_crypto_migrate_dir")),
	encryptionGetState: () => typedError<EncryptionStateResult, AppError>(__TAURI_INVOKE("encryption_get_state")),
	encryptionSubmitPassword: (password: string, createIfMissing: boolean | null) => typedError<EncryptionSubmitResult, AppError>(__TAURI_INVOKE("encryption_submit_password", { password, createIfMissing })),
	encryptionEnable: (password: string) => typedError<null, AppError>(__TAURI_INVOKE("encryption_enable", { password })),
	encryptionUnlock: (password: string) => typedError<null, AppError>(__TAURI_INVOKE("encryption_unlock", { password })),
	encryptionLock: () => typedError<null, AppError>(__TAURI_INVOKE("encryption_lock")),
	encryptionEncryptNotePayload: (plainBytes: number[]) => typedError<RawJson, AppError>(__TAURI_INVOKE("encryption_encrypt_note_payload", { plainBytes })),
	encryptionDecryptNotePayload: (payload: RawJson) => typedError<number[] | null, AppError>(__TAURI_INVOKE("encryption_decrypt_note_payload", { payload })),
	/**
	 *  Encrypt a sync payload (commit / snapshot / genesis) with the items key using
	 *  XChaCha20-Poly1305. `aad` binds the ciphertext to its identity (e.g. the file
	 *  stem) so it cannot be swapped between sync entries.
	 * 
	 *  The Yjs update is passed as base64-encoded raw bytes (`data`) rather than a
	 *  JSON number array, so multi-MB payloads never hit a serde_json round-trip on
	 *  a huge array (the previous ~950ms cost). `meta` (device/ts/seq/noteId) is
	 *  stored inside the encrypted envelope so it round-trips with the payload.
	 */
	syncEncryptPayload: (meta: string, data: string, aad: string) => typedError<string, AppError>(__TAURI_INVOKE("sync_encrypt_payload", { meta, data, aad })),
	/**
	 *  Decrypt a sync payload. Returns `DECRYPT_FAILED` on authentication failure
	 *  (wrong passphrase or tampered AAD) and `KEY_LOCKED` when the key is absent.
	 * 
	 *  Returns the decrypted update as base64 raw bytes plus the meta object, so the
	 *  renderer never reconstructs a giant number array. v4 envelopes (update stored
	 *  as a JSON number array) are decoded for backward compatibility.
	 */
	syncDecryptPayload: (enc: string, aad: string) => typedError<SyncDecryptedPayload, AppError>(__TAURI_INVOKE("sync_decrypt_payload", { enc, aad })),
	/**
	 *  Batch-encrypt a list of sync payloads in parallel. All items must succeed;
	 *  if any encryption fails the whole batch returns an error.
	 */
	syncEncryptBatch: (metas: string[], dataB64s: string[], aads: string[]) => typedError<string[], AppError>(__TAURI_INVOKE("sync_encrypt_batch", { metas, dataB64s, aads })),
	/**
	 *  Batch-decrypt a list of sync payloads in parallel. Each envelope is
	 *  decrypted independently; failed items produce `None` in the result vec
	 *  instead of aborting the whole batch.
	 */
	syncDecryptBatch: (envelopes: string[], aads: string[]) => typedError<(SyncDecryptedPayload | null)[], AppError>(__TAURI_INVOKE("sync_decrypt_batch", { envelopes, aads })),
	syncKeyReady: () => __TAURI_INVOKE<boolean>("sync_key_ready"),
	/**
	 *  Keep the local manifest and the shared `keyParams.json` in the sync folder
	 *  consistent so every device derives the same items key. `passphrase` is needed
	 *  to adopt a remote items key on a joining device (it is never written out).
	 */
	encryptionReconcileKeyParams: (passphrase: string | null) => typedError<null, AppError>(__TAURI_INVOKE("encryption_reconcile_key_params", { passphrase })),
	/**
	 *  Join an existing vault by adopting the shared key params found in the sync
	 *  source. Unlike `encryption_reconcile_key_params`, this works with an inactive
	 *  session (a fresh joining device has no manifest yet). Wrong passphrase returns
	 *  `WrongPassword` without touching any vault state.
	 */
	encryptionAdoptKeyParams: (passphrase: string, keyParams: string | null) => typedError<EncryptionSubmitResult, AppError>(__TAURI_INVOKE("encryption_adopt_key_params", { passphrase, keyParams })),
	/**
	 *  True when the configured sync source holds vault key params that differ from
	 *  this device's local manifest (or when no local manifest exists).
	 */
	encryptionHasRemoteKeyParams: () => typedError<boolean, AppError>(__TAURI_INVOKE("encryption_has_remote_key_params")),
	passwdHash: (password: string) => typedError<string, AppError>(__TAURI_INVOKE("passwd_hash", { password })),
	passwdCompare: (password: string, hash: string) => typedError<boolean, AppError>(__TAURI_INVOKE("passwd_compare", { password, hash })),
	passwdRecordFailure: () => typedError<FailureResult, AppError>(__TAURI_INVOKE("passwd_record_failure")),
	passwdResetFailures: () => typedError<null, AppError>(__TAURI_INVOKE("passwd_reset_failures")),
	encryptionDecryptAssetStream: (path: string) => typedError<string, AppError>(__TAURI_INVOKE("encryption_decrypt_asset_stream", { path })),
	encryptionEncryptAssetStream: (path: string) => typedError<null, AppError>(__TAURI_INVOKE("encryption_encrypt_asset_stream", { path })),
	encryptionCacheDecryptedNote: (noteId: string, content: number[]) => typedError<null, AppError>(__TAURI_INVOKE("encryption_cache_decrypted_note", { noteId, content })),
	encryptionGetCachedDecryptedNote: (noteId: string) => __TAURI_INVOKE<number[] | null>("encryption_get_cached_decrypted_note", { noteId }),
	encryptionClearDecryptedCaches: () => typedError<null, AppError>(__TAURI_INVOKE("encryption_clear_decrypted_caches")),
	decryptLegacyCryptojsNote: (ciphertextB64: string, password: string) => typedError<string, AppError>(__TAURI_INVOKE("decrypt_legacy_cryptojs_note", { ciphertextB64, password })),
	deriveArgon2Key: (passphrase: string, salt: string | null) => typedError<string, AppError>(__TAURI_INVOKE("derive_argon2_key", { passphrase, salt })),
	dialogOpen: (props: OpenDialogOptions) => typedError<DialogResult, AppError>(__TAURI_INVOKE("dialog_open", { props })),
	dialogMessage: (props: MessageDialogOptions) => typedError<null, AppError>(__TAURI_INVOKE("dialog_message", { props })),
	dialogSave: (props: SaveDialogOptions) => typedError<SaveDialogResult, AppError>(__TAURI_INVOKE("dialog_save", { props })),
	getSystemFonts: () => typedError<string[], AppError>(__TAURI_INVOKE("get_system_fonts")),
	getInstallationSource: () => __TAURI_INVOKE<InstallationSource>("get_installation_source"),
	checkForUpdates: () => typedError<CheckResult, AppError>(__TAURI_INVOKE("check_for_updates")),
	downloadUpdate: () => typedError<null, AppError>(__TAURI_INVOKE("download_update")),
	installUpdate: () => typedError<null, AppError>(__TAURI_INVOKE("install_update")),
	toggleAutoUpdate: (enabled: boolean) => typedError<null, AppError>(__TAURI_INVOKE("toggle_auto_update", { enabled })),
	getAutoUpdateStatus: () => typedError<boolean, AppError>(__TAURI_INVOKE("get_auto_update_status")),
	isUpdateDownloading: () => typedError<boolean, AppError>(__TAURI_INVOKE("is_update_downloading")),
	getUpdateInfo: () => typedError<UpdateInfo, AppError>(__TAURI_INVOKE("get_update_info")),
	importEvernote: (enexPath: string, notebookName: string | null) => typedError<null, AppError>(__TAURI_INVOKE("import_evernote", { enexPath, notebookName })),
	importAppleNotes: () => typedError<null, AppError>(__TAURI_INVOKE("import_apple_notes")),
	renderPdf: (html: string, outputPath: string) => typedError<null, AppError>(__TAURI_INVOKE("render_pdf", { html, outputPath })),
	/**
	 *  Append a single Yjs binary update for a note.  Updates are stored as
	 *  append-only BLOB rows so every peer's version is preserved.
	 *  When app encryption is active the blob is encrypted before persisting.
	 *  Dispatched to a blocking thread so AES + SQLite never block the event loop.
	 *  The update crosses IPC as base64 (Tauri invoke is JSON-only; base64 is
	 *  ~3x smaller than the JSON number-array encoding this replaced).
	 */
	yjsAppend: (noteId: string, update: string, device: string) => typedError<null, AppError>(__TAURI_INVOKE("yjs_append", { noteId, update, device })),
	/**
	 *  Append multiple Yjs binary updates in a single IPC call.
	 *  All updates are inserted inside one SQLite transaction.
	 */
	yjsAppendBatch: (noteIds: string[], updates: string[], devices: string[]) => typedError<number, AppError>(__TAURI_INVOKE("yjs_append_batch", { noteIds, updates, devices })),
	/**
	 *  Return every stored Yjs update for a note, oldest first.
	 *  The caller replays them into a Y.Doc to reconstruct the current state.
	 */
	yjsGetUpdates: (noteId: string) => typedError<string[], AppError>(__TAURI_INVOKE("yjs_get_updates", { noteId })),
	/**
	 *  Return a cached merged Yjs state snapshot for a note when it is fresh
	 *  (no stored update is newer than the snapshot). Returns an empty string when
	 *  the caller must replay history and re-cache it via `yjs_save_snapshot`.
	 *  Dispatched to a blocking thread: the stale path replays and decrypts the
	 *  whole update history, which must not block the event loop.
	 */
	yjsGetSnapshot: (noteId: string) => typedError<string, AppError>(__TAURI_INVOKE("yjs_get_snapshot", { noteId })),
	/**
	 *  Return the fresh merged Yjs snapshot for many notes in a single round-trip
	 *  (batched SQL), avoiding N+1 IPC calls. Only requested notes that have data
	 *  are included in the result map.
	 *  Dispatched to a blocking thread (rayon parallel decrypt inside).
	 */
	yjsGetSnapshots: (noteIds: string[]) => typedError<{ [key in string]: string }, AppError>(__TAURI_INVOKE("yjs_get_snapshots", { noteIds })),
	/**
	 *  Delete all existing updates for a note and replace them with a single
	 *  compressed Yjs state vector (snapshot).  Keeps the row count bounded.
	 *  Dispatched to a blocking thread: rewrites every row + encrypts a multi-MB
	 *  blob on note switch.
	 */
	yjsCompact: (noteId: string, snapshot: string) => typedError<null, AppError>(__TAURI_INVOKE("yjs_compact", { noteId, snapshot })),
	/**
	 *  Read all updates for a note, merge them into a single snapshot via y-octo,
	 *  replace the old rows with one compacted row, and keep the snapshot cache in
	 *  sync — all in a single SQLite transaction.
	 */
	yjsCompactBatch: (noteId: string) => typedError<null, AppError>(__TAURI_INVOKE("yjs_compact_batch", { noteId })),
	/**  Delete every Yjs update for a note.  Called when the note itself is deleted. */
	yjsDelete: (noteId: string) => typedError<null, AppError>(__TAURI_INVOKE("yjs_delete", { noteId })),
	indexSave: (searchJson: string, linksJson: string, signaturesJson: string) => typedError<null, AppError>(__TAURI_INVOKE("index_save", { searchJson, linksJson, signaturesJson })),
	indexLoad: () => typedError<{
	searchJson: string,
	linksJson: string,
	signaturesJson: string,
} | null, AppError>(__TAURI_INVOKE("index_load")),
	/**
	 *  Extract search index data from all notes in the data store.
	 *  Runs off-main-thread via `spawn_blocking` so the UI stays responsive.
	 *  Returns a flat array of `{ id, title, searchText, labelsText }` entries
	 *  ready for MiniSearch to consume on the JS side.
	 */
	searchExtractIndexData: () => typedError<SearchEntry[], AppError>(__TAURI_INVOKE("search_extract_index_data")),
	/**  Return all registered workspaces. */
	workspaceList: () => typedError<WorkspaceInfo[], AppError>(__TAURI_INVOKE("workspace_list")),
	/**  Return the currently active workspace. */
	workspaceGetActive: () => typedError<WorkspaceInfo, AppError>(__TAURI_INVOKE("workspace_get_active")),
	/**  Create a new workspace and switch to it. */
	workspaceCreate: (name: string, copySettings: boolean | null) => typedError<WorkspaceInfo, AppError>(__TAURI_INVOKE("workspace_create", { name, copySettings })),
	/**
	 *  Register a backend (cloud) workspace in the local registry so local mirrors
	 *  of shared/cloud workspaces participate in removal reconciliation. Creates
	 *  the workspace directory and DBs on first registration (like `workspace_create`),
	 *  upserts the entry, and never changes the active workspace.
	 */
	workspaceRegisterCloud: (id: string, name: string, orgId: string | null, ownerId: string | null, workspaceType: string | null, createdAt: string | null) => typedError<WorkspaceInfo, AppError>(__TAURI_INVOKE("workspace_register_cloud", { id, name, orgId, ownerId, workspaceType, createdAt })),
	/**  Switch the active workspace. The frontend must reload stores after this. */
	workspaceSwitch: (id: string) => typedError<null, AppError>(__TAURI_INVOKE("workspace_switch", { id })),
	/**  Rename a workspace. */
	workspaceRename: (id: string, name: string) => typedError<null, AppError>(__TAURI_INVOKE("workspace_rename", { id, name })),
	/**
	 *  Delete a workspace. Cannot delete the currently active workspace.
	 *  The workspace directory and all its data are removed.
	 */
	workspaceDelete: (id: string) => typedError<null, AppError>(__TAURI_INVOKE("workspace_delete", { id })),
};

/* Types */
export type AppError = ({ Io: string }) & { Crypto?: never; Other?: never; Serialization?: never } | ({ Crypto: string }) & { Io?: never; Other?: never; Serialization?: never } | ({ Serialization: string }) & { Crypto?: never; Io?: never; Other?: never } | "WrongPassword" | "EncryptionLocked" | "DevicePasswordRequired" | "WrongDevicePassword" | "SecureStorageUnavailable" | ({ Other: string }) & { Crypto?: never; Io?: never; Serialization?: never };

export type AppInfo = {
	name: string,
	version: string,
};

export type AssetMigrationResult = {
	total: number,
	processed: number,
	failedPaths: string[],
};

export type CheckResult = {
	success: boolean,
	available: boolean,
	version: string | null,
	error: string | null,
};

export type DialogFilter = {
	name: string,
	extensions: string[],
};

export type DialogResult = {
	canceled: boolean,
	filePaths: string[],
};

export type EncryptionStateResult = {
	enabled: boolean,
	unlocked: boolean,
	appEnabled: boolean,
	appUnlocked: boolean,
};

export type EncryptionSubmitResult = {
	ok: boolean,
	error: string | null,
	state: EncryptionStateResult,
};

export type FailureResult = {
	failCount: number,
	warn: boolean,
	/**  True when the unlock is currently rate-limited (lockout active). */
	locked: boolean,
	/**  Seconds remaining in the current lockout (0 when not locked). */
	lockoutSeconds: number | null,
};

export type FileStat = {
	isFile: boolean,
	isDirectory: boolean,
	size: number | null,
	mtimeMs: number | null,
	ctimeMs: number | null,
};

export type IndexSnapshot = {
	searchJson: string,
	linksJson: string,
	signaturesJson: string,
};

export type InstallationSource = "standalone" | "scoop" | "brew" | "linuxPackage" | "appStore";

export type LegacyMigrationResult = {
	legacyDir: string | null,
	appDir: string | null,
	mergedStoreFiles: string[],
	copiedAssetDirs: string[],
	markerWritten: boolean,
};

export type LegacyMigrationStatus = {
	legacyDir: string | null,
	appDir: string | null,
	hasLegacyData: boolean,
	alreadyMigrated: boolean,
	targetHasData: boolean,
};

/**
 *  Which secure backend currently protects the master key. Mirrors the OS
 *  keychain on macOS/Windows/iOS, Secret Service or the kernel keyring on
 *  Linux, and Android Keystore on Android. `EncryptedFile` is the Linux
 *  device-password fallback.
 */
export type MasterKeyBackendKind = "keychain" | "secretService" | "kernelKeyring" | "encryptedFile" | "androidKeystore" | "none";

export type MessageDialogOptions = {
	title: string | null,
	message: string,
	type: string | null,
	buttons: string[] | null,
};

export type OpenDialogOptions = {
	title: string | null,
	defaultPath: string | null,
	directory: boolean | null,
	multiple: boolean | null,
	properties: string[] | null,
	filters: DialogFilter[] | null,
};

/**
 *  Wrapper around `serde_json::Value` that specta exports as TypeScript `any`.
 *  This avoids the infinite-loop bug in specta-typescript when trying to render
 *  the recursive `serde_json::Value` enum definition.
 */
export type RawJson = any;

export type SafeStorageBackendInfo = {
	available: boolean,
	backend: MasterKeyBackendKind,
	devicePasswordRequired: boolean,
};

export type SaveDialogOptions = {
	title: string | null,
	defaultPath: string | null,
	filters: DialogFilter[] | null,
};

export type SaveDialogResult = {
	canceled: boolean,
	filePath: string | null,
};

export type SearchEntry = {
	id: string,
	title: string,
	searchText: string,
	labelsText: string,
};

export type SyncDecryptedPayload = {
	meta: SyncMeta,
	update: string,
};

export type SyncMeta = {
	device: string,
	ts: number,
	seq?: number | null,
	noteId: string,
};

export type UpdateInfo = {
	isChecking: boolean,
	isDownloading: boolean,
	currentVersion: string | null,
	availableVersion: string | null,
	autoUpdateEnabled: boolean,
	isBusy: boolean,
};

export type WorkspaceInfo = {
	id: string,
	name: string,
	createdAt: string,
	workspaceType?: string,
	orgId?: string | null,
	ownerId?: string | null,
	cloudSync?: boolean,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

